networks:
    docker_common_network:
        external: true

services:
  app:
    container_name: filestash
    build:
        context: .
        dockerfile: Dockerfile
    restart: always
    environment:
    - APPLICATION_URL=
    - ONLYOFFICE_URL=http://onlyoffice
    - CANARY=true
    networks:
        - docker_common_network
    ports:
    - "8334:8334"
    volumes:
    - filestash:/app/data/state/

  onlyoffice:
    container_name: filestash_oods
    image: onlyoffice/documentserver:7.1
    restart: always

volumes:
    filestash: {}
